project:

  type: website
 
website:

  title: ""

  navbar:

    left:

    - text: "Hands_on_Exercises"

      menu:

        - text: "1a: Geospatial Data Wrangling with R"

          href: "Hands_on_Exercises/Hands_on_Ex01/Hands_on_Ex01a.html"

    right:

      - href: index.qmd

        text: Home

      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
