{
  "hash": "8ca9dd92fba3cab043e754077f2858b7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 1: Geospatial Analytics for Public Good\"\nauthor: \"Deepika Raja\"\ndate: \"September 15, 2025\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\nformat: \n  html:\n    toc: true\n    code-link: true\nnumber-sections: true\nnumber-depth: 4\neditor: visual\n---\n\n\n\n# 1. Research Focus\n\nThis study looks at where and how new businesses are emerging in Singapore. By applying **spatial point pattern analysis**, I will explore:\n\n-   how **densely** new businesses are distributed across the island,\n\n-   whether **clustering** occurs in certain regions or industries,\n\n-   how business locations relate to one another **spatially**, and\n\n-   how these patterns shift between **2024 and the first half of 2025**.\n\nThrough this, the analysis highlights short-term trends in Singapore’s commercial landscape and uncovers the early signs of potential growth hubs.\n\n# 2. Objectives\n\nThis study aims to analyse the spatial and spatio-temporal dynamics of newly established businesses in Singapore during the first half of 2025. The key objectives are:\n\n1.  **Locate patterns of emergence** — Identify *where* and *when* new businesses are concentrated, highlighting clusters and spatial trends relevant to urban planning and economic development.\n\n2.  **Uncover interactions** — Examine how businesses relate beyond simple density, including clustering of similar industries, temporal shifts, and structural changes in commercial zones.\n\n3.  **Support decision-making** — Translate spatial insights into knowledge that can guide planning, resource allocation, and strategies for fostering sustainable business growth.\n\n# 3. Installing and Loading R Packages\n\nBefore starting the analysis, it is important to ensure that the required R packages are available in the working environment. These packages provide the tools for handling geospatial data, performing spatial point pattern analysis, creating maps, and producing visual outputs.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf,tmap,tidyverse,sparr,terra,spatstat,\n               rvest,httr,knitr, ggthemes, plotly,DT)\n\n# For reproducibility\nset.seed(1234)\n\n# Set tmap to plot mode\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n# 4. The Data\n\nFor this exercise, the analysis uses **three primary datasets**, all publicly available from [data.gov.sg](http://data.gov.sg):\n\n## 4.a. Master Plan 2019 Subzone Boundary (No Sea) (KML)\n\n-   Contains the polygon boundaries of Singapore’s subzones (excluding sea areas).\n-   Provides the spatial framework for mapping and analyzing business locations relative to urban subzones.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- st_read(\"data/MasterPlan2019SubzoneBoundaryNoSeaKML.kml\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `URA_MP19_SUBZONE_NO_SEA_PL' from data source \n  `C:\\deepikarcodes\\ISSS626-GAA\\Take_Home_Exercises\\Take_Home_Ex01\\data\\MasterPlan2019SubzoneBoundaryNoSeaKML.kml' \n  using driver `KML'\nSimple feature collection with 332 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\nThe KML file `MasterPlan2019SubzoneBoundaryNoSeaKML.kml` was successfully loaded using the KML driver. It contains a simple feature collection of 332 multipolygon features with two attribute fields. Each feature corresponds to a URA Master Plan 2019 subzone (excluding sea areas) and is defined using two-dimensional geographic coordinates (longitude and latitude) under the WGS 84 coordinate system. The dataset spans the entirety of Singapore, with a bounding box approximately from 103.61°E to 104.09°E longitude and 1.16°N to 1.47°N latitude.\n\nNext, we will extract the relevant information from the HTML source.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_kml_field <- function(html_text, field_name) {\n  if (is.na(html_text) || html_text == \"\") return(NA_character_) # check if text is na\n  \n  page <- read_html(html_text)\n  rows <- page %>% html_elements(\"tr\") # find table row element \n  \n  value <- rows %>%\n    # looks through each row to find table header == field_name and\n    keep(~ html_text2(html_element(.x, \"th\")) == field_name) %>% \n    html_element(\"td\") %>% # extract table data\n    html_text2() # and then extract clean text context\n  \n  if (length(value) == 0) NA_character_ else value # return value if is not NA\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- mppa %>%\n  mutate(REGION_N = map_chr(Description,extract_kml_field,\"REGION_N\"),\n         PLN_AREA_N = map_chr(Description,extract_kml_field,\"PLN_AREA_N\"))%>%\n  select(-Name, -Description) %>% # unselect columns \"Name\" and \"Description\"\n  relocate(geometry, .after = last_col()) # move the \"geometry\" to the end\n```\n:::\n\n\n\nWe transform the dataset’s coordinate reference system (CRS) from WGS84 (EPSG:4326) to SVY21 (EPSG:3414) to enhance accuracy and support further spatial analyses. This conversion changes all feature coordinates from (latitude, longitude) in degrees to (x, y) in meters within Singapore’s SVY21 system.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- mppa %>%\n    #Removes Z (elevation) and M (measure) dimensions from the geometry if they exist\n  st_zm(drop = TRUE, what = \"ZM\") %>% \n  st_transform(crs = 3414)\nst_geometry(mppa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 332 features \nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mppa,\"data/rds/mppa.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- read_rds(\"data/rds/mppa.rds\")\n```\n:::\n\n\n\n### 4.a.1. Let's plot planning area in SG:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa) +\n  tm_polygons(\n      col = \"REGION_N\",\n      palette = \"Set3\",  # updated color palette\n      lwd = 0.5\n  ) +\n  tm_text(\n      \"PLN_AREA_N\", size = 0.4,\n      auto.placement = TRUE,\n      remove.overlap = TRUE\n  ) +\n  tm_title(\n      \"SG Planning Area\",\n      position = tm_pos_out(\"center\", \"top\", \"center\")\n  ) +\n  tm_legend(\n      frame = FALSE,\n      position = c(\"right\", \"bottom\")\n  ) +\n  tm_layout(\n      frame = FALSE,\n      bg.color = \"#f6f6f6\"\n  )\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_Final_files/figure-html/unnamed-chunk-8-1.png){width=1152}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa_sf <- mppa %>%\n  filter (PLN_AREA_N != \"CENTRAL WATER CATCHMENT\",\n          PLN_AREA_N != \"WESTERN WATER CATCHMENT\",\n         PLN_AREA_N != \"WESTERN ISLANDS\",\n         PLN_AREA_N != \"SOUTHERN ISLANDS\",\n         PLN_AREA_N != \"NORTH-EASTERN ISLANDS\",\n         )\n```\n:::\n\n\n\nWe focus on Singapore’s main island, excluding non-commercial areas, to accurately show business-related spatial patterns. Now, we plot the area again :\\\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa_sf) +\n  tm_polygons(col =\"REGION_N\",\n              palette = \"Pastel2\",\n              lwd = 0.5) +\n  tm_text(\"PLN_AREA_N\", size=0.4,\n          auto.placement = TRUE,\n          remove.overlap = TRUE) +\n  tm_title(\"SG Planning Area - Business Activities\",\n           position = tm_pos_out(\"center\", \"top\", \"center\")) +\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\")) +\n  tm_layout(frame = FALSE,\n            bg.color = \"#e9f4f8\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_Final_files/figure-html/unnamed-chunk-10-1.png){width=1152}\n:::\n:::\n\n\n\n## 4.b. Corporate Entities Dataset (ACRA)\n\n-   Contains corporate registration information for businesses in Singapore, including incorporation date and SSIC 2020 codes.\n\n-   For this exercise, we extracted **new business entities registered between 1 January 2024 and 30 June 2025**, and filtered them based on relevant SSIC codes to focus on selected business types.\n\nThese datasets together enable **spatial and spatio-temporal analysis** of new business clusters, trends, and interactions within Singapore’s urban environment.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfolder_path <- \"data/ACRA\"\nfile_list <- list.files(path = folder_path,\n                        pattern = \"^ACRA*.*\\\\.csv$\",\n                        full.names = TRUE)\nacra <- file_list %>%\n  map_dfr(read_csv)\n```\n:::\n\n\n\n### 4.b.1 Filtering SSIC Data:\n\nExtract selected data for three industries: Food and Beverages (SSIC 56111), Management Consultancy (SSIC 70201), and Information Technology (SSIC 62011) from January to June 2025:\n\n```{}\n```\n\n## 4.c. Geocoding Business Locations\n\nThe ACRA dataset does not include latitude and longitude; it only provides postal codes and addresses. To map these locations, we need **geocoding**—converting textual location information into precise geographic coordinates.\n\nFor this project, we use **OneMap**, Singapore’s official geospatial platform, to geocode each postal code. The API returns accurate coordinates, enabling us to plot business locations on a map and conduct spatial analyses such as clustering, density estimation, and proximity calculations. This step is crucial because spatial operations require numerical coordinates rather than just addresses.\n\n### 4.c.1. Combining the data by row:\n\n```{}\n```\n\n### 4.c.2. Saving Combined Dataset\n\n### 4.c.3. Extracting Unique postal codes from extracted data:\n\n```{}\n```\n\nThere are 1925 unique observations.\n\nNext, we utilize the **httr** package to make a GET request to the OneMap API in order to obtain geographic coordinates:\n",
    "supporting": [
      "Take_Home_Ex01_Final_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}